### ISSUE TITLE
PDF?

### ISSUE THREAD

**Issue by robertamezquita** [LTLA/AntiMagic2018#1]
You wouldn't happen to have a compiled PDF snapshot do you? Just for the sake of easy perusing of the results. 

Great read nonetheless though. Favorite line so far:

"One might dismiss the previous simulation as being somewhat pathological. After all, there are no biological systems that exhibit no structure whatsoever."

So good.

**Comment by LTLA** [comment]
I used to have a link to a PDF, but I was directed to get rid of it. I've sent it to you off-line.
